package com.uog.clearance.audit.model;

public enum AuditAction {
    USER_CREATED,
    USER_UPDATED,
    USER_STATUS_CHANGED,
    USER_DELETED,
    STUDENT_CREATED,
    STUDENT_UPDATED,
    STUDENT_MEDIA_UPDATED,
    STUDENT_STATUS_CHANGED,
    CLEARANCE_REQUEST_CREATED,
    LIABILITY_CREATED,
    LIABILITY_UPDATED,
    LIABILITY_CLEARED,
    CHECK_REVIEWED,
    PAYMENT_INITIATED,
    PAYMENT_VERIFIED,
    MANUAL_PAYMENT_RECORDED,
    FINANCE_RECEIPT_ISSUED,
    QR_GENERATED,
    QR_SENT_TO_STUDENT,
    REGISTRAR_CLOSED,
    QR_VERIFIED
}
